Repository Averyyyyyyyy/dnd-bot, pull requests merged in 2022-01, with the labels that each got.

#2 feat: readme
  README.md
Labels: documentation

#8 refactor: added option to turn debug on and off
  .example.env
  src/util/logger.ts
Labels: type: enhancement, priority: low

#12 Events
  .example.env
  src/commands/world.ts
  src/components/worldSelection.ts
  src/events/debug.ts
  src/events/error.ts
  src/events/interactionCreate.ts
  src/events/rateLimit.ts
  src/events/ready.ts
  src/events/warn.ts
  src/index.ts
  src/interactions/selectMenu/worldSelection.ts
  src/models/Character.ts
  src/models/User.ts
  src/models/World.ts
  src/scripts/slashCommands/deployGlobal.ts
  src/scripts/slashCommands/deployGuild.ts
  src/subcommands/createCharacter.ts
  src/subcommands/createWorld.ts
  src/subcommands/selectWorld.ts
  src/subcommands/showCharacter.ts
  src/util/executeSubcommand.ts
  src/util/logger.ts
Labels: Type: Enhancement, Priority: Low, Status: Needs Review
